name: CD - Deploy to Kubernetes

on:
  push:
    branches: ["main"]
    paths:
      - 'app/**'
      - 'k8s/**'
      - 'Dockerfile'
      - '.github/workflows/**'

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'
      - name: Write kubeconfig
        shell: bash
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_DATA}" | base64 -d > $HOME/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      - name: Create namespace (idempotent)
        run: kubectl apply -f k8s/namespace.yaml
      - name: Apply manifests
        run: kubectl -n ai-demo apply -f k8s/service.yaml -f k8s/deployment.yaml
      - name: Update image to latest
        run: |
          kubectl -n ai-demo set image deployment/ai-demo api=ghcr.io/${{ github.repository }}:latest --record
      - name: Wait for rollout
        run: kubectl -n ai-demo rollout status deployment/ai-demo --timeout=120s
